// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDatxAltC9j9-GCwPm8NGczsm-0Iq7m8Qo',
    appId: '1:608449692297:android:0f028141fcb3bb50937c58',
    messagingSenderId: '608449692297',
    projectId: 'aloolahma-1886f',
    databaseURL: 'https://aloolahma-1886f-default-rtdb.firebaseio.com',
    storageBucket: 'aloolahma-1886f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB634Xx_VJJSDTsiBQ5IvxaIQYY4oKOcfk',
    appId: '1:608449692297:ios:e2fea0429a0cfe2c937c58',
    messagingSenderId: '608449692297',
    projectId: 'aloolahma-1886f',
    databaseURL: 'https://aloolahma-1886f-default-rtdb.firebaseio.com',
    storageBucket: 'aloolahma-1886f.appspot.com',
    androidClientId: '608449692297-btvhqc8t7s1j6d3phb1m4h52iupcnfb4.apps.googleusercontent.com',
    iosClientId: '608449692297-a6tuldl54bng0abf42p20e96r79il63q.apps.googleusercontent.com',
    iosBundleId: 'com.aloolahma.drivers',
  );
}
